### Create a new patient entity
POST http://localhost:4004/api/patients
Authorization: Bearer {{token}}
Content-Type: application/json


{
  "name": "King Jerry Kafka",
  "email": "kingJerry@example.com",
  "address": "2122 main street",
  "dateOfBirth": "1995-10-11",
  "registeredDate": "2024-02-12"
}

###