### update an existing patient
PUT http://localhost:4004/api/patients/77a0f998-95c5-4442-b7be-ff30f1267f27
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Chimp Ken",
  "email": "chimpKen@example.com",
  "address": "898 Willow St, Springfield",
  "dateOfBirth": "1987-10-17"
}
