### update an existing patient
PUT http://localhost:4004/api/patients/123e4567-e89b-12d3-a456-426614174001
Content-Type: application/json

{
  "name": "Ken Den UPDATED2",
  "email": "ken@example.com",
  "address": "2236 main street 6",
  "dateOfBirth": "1994-10-05"
}
